### PR TITLE
Add the option to create trays for miniatures instead of boxes

### PR DESCRIPTION
**Pull request by fhp**
The code for this module was originally created by "fidoriel" and can be found at https://github.com/fidoriel/Mini-Tray

This code is licensed under the GPL v3 license. Merging this PR will imply that this repo will also be licensed as GPL v3.

That said, this PR might be considered scope-creep, so feel free to close the PR if you think it doesn't fit in this project.

### CODE REVIEW

**Comment by Alex9779** [comment]
OK so this is nice. I stumbled over the try project too a while ago.
But I personally have no use for this.
And then there is the thing with the license. Originally this project was posted on Thingyverse, later on Printables always under CC-BY-SA. Unfortunately I never added the license here.
So acutally to be constistent I would have to add CC-BY-SA here and then I have no idea how to handle this legally, I don't know much about that license stuff.

Open for suggestions but I think this would be better suited in a fork and published by you...

**Comment by fhp** [comment]
License wise, CC-BY-SA can be converted into GPL, not the other way around. So I can fork your code, merge with the GPL code and publish as GPL.

I can also make a PR for just the [Add a tray mode.](https://github.com/Alex9779/IKEA-Samla-Inserts/pull/17/commits/bc3cb157d2f5394cf297da67c717ca9c9f1c94a9) commit, that is my own code, so no license issues there, and less specific for miniatures.

But I'm also happy to just fork and publish myself.

**Comment by Alex9779** [comment]
> License wise, CC-BY-SA can be converted into GPL, not the other way around. So I can fork your code, merge with the GPL code and publish as GPL.

good to know, thx...

> I can also make a PR for just the [Add a tray mode.](https://github.com/Alex9779/IKEA-Samla-Inserts/pull/17/commits/bc3cb157d2f5394cf297da67c717ca9c9f1c94a9) commit, that is my own code, so no license issues there, and less specific for miniatures.

Hmmmm, what is a use case to have trays without the slots?

Regarding the mini-figure code: to be honest I don't want code for a feature I don't use directly in the project. I would have to maintain it if I change something or if the base project changes. I could maybe easily break it and not even realized it because I will never use this in practice.

Actually I thought about extracting the code for the Samla content to some external module to make it reusable for other projects.

**Comment by fhp** [comment]
> Hmmmm, what is a use case to have trays without the slots?

Not sure about that ether.

> Regarding the mini-figure code: to be honest I don't want code for a feature I don't use directly in the project. I would have to maintain it if I change something or if the base project changes. I could maybe easily break it and not even realized it because I will never use this in practice.

Makes sense, it's a hobby project without unit tests and such after all ;)

> Actually I thought about extracting the code for the Samla content to some external module to make it reusable for other projects.

That would be nice :)

I'll close this PR then, and make and maintain my [own fork](https://github.com/fhp/IKEA-Samla-Inserts) and Thingiverse post.

**Pull request closed without merging**
